title: Firmware installation menu
hero_image: images/banner.png
description: firmware-installation-menu description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-28"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
